3-http:
  image: docker:latest
  stage: test
  services:
    - docker:dind
  before_script:
    - apk add --no-cache docker-compose
  script:
    - cd 3-http
    - docker-compose build server tests
    - docker-compose up -d server
    - docker-compose run --rm tests
  rules:
    - changes:
        - $CI_JOB_NAME/**/*
        - .gitlab-ci/$CI_JOB_NAME.yml
