3-http:
  extends: .hw-test
  image: docker:latest
  stage: test
  services:
    - docker:dind
  before_script:
    - apk add --no-cache go=1.18.6-r0
  script:
    - cd 3-http
    - docker build ./server -t hw3img
    - cd tests
    - export USE_DOCKER=1
    - go test
