3-http:
  extends: .hw-test
  image: docker:latest
  stage: test
  services:
    - docker:dind
  before_script:
    - apk add --no-cache docker-compose
  script:
    - cd 3-http
    - docker-compose build server tests
    - docker-compose up -d server
    - docker-compose run --rm tests
